---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)

library(plotly)
data(instacart)
```



Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart %>%
  count(aisle) %>% 
  filter(n > 10000) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(
    x =~aisle, y=~n, type = "scatter", mode = "markers",
    alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart %>%
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>%
  group_by(product_name, order_dow) %>%
  mutate(product_name = fct_reorder(product_name, order_hour_of_day )) %>% 
  plot_ly(y=~order_hour_of_day, color = ~product_name, type = "box", colors = "viridis")
```

### Chart C

```{r}
instacart %>% 
  count(aisle) %>% 
  filter(n > 10000) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>%
  plot_ly(
    x =~aisle, y=~n, type = "bar", mode = "markers",color = ~aisle,
    alpha = 0.5)
```

```{r}
rmarkdown::render("flex_dashboard.Rmd", output_format = "flexdashboard::flex_dashboard")
```


